CI: WIP DEBUG rename error
Currently, windows build fails in CI with:

```
Error renaming from "D:/a/FreeImageRe/FreeImageRe/build/dav1d/install/lib/libdav1d.a" to "D:/a/FreeImageRe/FreeImageRe/build/dav1d/install/lib/libdav1d_deb.lib": No error
NMAKE : fatal error U1077: 'echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -E rename D:/a/FreeImageRe/FreeImageRe/build/dav1d/install/lib/libdav1d.a D:/a/FreeImageRe/FreeImageRe/build/dav1d/install/lib/libdav1d_deb.lib' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\nmake.exe" -s -f CMakeFiles\DAVID.dir\build.make /nologo -SL                 CMakeFiles\DAVID.dir\build' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\nmake.exe" -s -f CMakeFiles\Makefile2 /nologo -SL                 CMakeFiles\DAVID.dir\all' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\nmake.exe" -s -f CMakeFiles\Makefile2 /nologo -S                  DAVID' : return code '0x2'
Stop.
Error: Process completed with exit code 1.
```

The first line `No error` does actually mean `file not found` [1].

Adding some echo to debug this.

[1] https://gitlab.kitware.com/cmake/cmake/-/issues/16345